buildscript {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:9.4.0'
    }
}

allprojects {
    version = '1.0.0'

    ext {
        appName = "Elementum"
        gdxVersion = '1.14.2'
        box2DLightsVersion = '1.4'
    }

    repositories {
        google()
        mavenCentral()
        maven { url "https://oss.sonatype.org/content/repositories/releases/" }
    }
}

project(":core") {
    apply plugin: "java-library"

    java {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }

    dependencies {
        api "com.badlogicgames.gdx:gdx:$gdxVersion"
        api "com.badlogicgames.gdx:gdx-box2d:$gdxVersion"
        implementation "com.badlogicgames.box2dlights:box2dlights:$box2DLightsVersion"
        implementation "org.dyn4j:dyn4j:3.4.0"
        implementation "org.locationtech.jts:jts-core:1.17.0"
    }
}
